Add options support
Genentech/checked pull request #39
Opened 2024-09-03 19:46 UTC by maksymiuks

Closes #37 
Closes #36

2024-09-03 20:08 UTC, dgkf-roche approved these changes
Looks good! A few suggestions for improvements, but nothing that should prevent us from merging and continuing to improve from there.

2024-09-03 20:08 UTC, dgkf-roche commented on R/check_design.R
> +        )
Maybe not immediately necessary, but it would be helpful to indicate what results were found.

2024-09-04 08:41 UTC, maksymiuks commented on R/options.R
> +  add_default_configuration = TRUE
Thanks, excellent points! I've refined the names and usage. Does it look better now?

2024-09-04 08:42 UTC, maksymiuks commented on R/check_design.R
> +        )
It is a good idea for the future, as it would be a bit tricky, as it is not that obvious what should be reported (libraries, installation status, check statuses etc)

2024-09-04 18:15 UTC, dgkf-roche commented on R/options.R
> +  default_check_args = TRUE
Instead of having a logical flag, then embedding some defaults in the package, we should just expose the defaults.

```suggestion
  "R CMD check related environment variables",
  default_check_env_variables = c(
    "_R_CHECK_FORCE_SUGGESTS_" = FALSE,
    "_R_CHECK_RD_XREFS_" = FALSE,
    "_R_CHECK_SYSTEM_CLOCK_" = FALSE,
    "_R_CHECK_SUGGESTS_ONLY_" = TRUE
  ),

  "R CMD check build args",
  default_check_build_args = c(
    "--no-build-vignettes",
    "--no-manual"
  ),

  "R CMD check args",
  default_check_args =c(
    "--timings",
    "--ignore-vignettes",
    "--no-manual"
  )
```

2024-09-20 10:27 UTC, maksymiuks commented on R/options.R
> +  default_check_args = TRUE
Honestly, I'd like to avoid that. These default options ensure that the checks are sane by default (for instance,`"_R_CHECK_SUGGESTS_ONLY_", which forces dependencies isolation). If we make them exposed defaults, then whenever someone adds their own option, it would overwrite defaults, which almost always should be used. Therefore, I'd like to stick to the mechanism when the user appends to the existing options, except when explicitly set otherwise.

2024-09-20 16:16 UTC, dgkf-roche commented on R/options.R
> +  default_check_args = TRUE
I think this is a matter of what we feel should be the purpose of `checked`. Personally, I want `checked` to be the best `R CMD check` orchestration tool. We have opinions on how to run `R CMD check` most rigorously, but I don't think it's the role of the tool to constrain how people choose to run checks themselves. 

This is why I want opinionated defaults, but to be flexible enough for other use cases.

If we assume that anyone who is investigating global flags to configure the tool is a savvy user, then I think we can trust them with the freedom to use the tool as they see fit.

If we're concerned about people overwriting defaults with flags that produce behaviors that they're not intending, then I think the solution is effective documentation to make the intention clear, not restricting the use of those flags.

2024-09-25 13:55 UTC, maksymiuks commented on R/options.R
> +  default_check_args = TRUE
Fair. Considering it and the online discussion we had, I've implemented options according to your suggestions.

2024-09-26 16:28 UTC, dgkf-roche requested changes
A couple minor requests - primarily just bolstering testing before we merge.

2024-09-26 16:28 UTC, dgkf-roche commented on tests/testthat/test-checks_df.R
> +)
Unclear why we define both `path` and `path_broken` here, and also suggest not defining the variable `names` (as it is ambiguous out-of-context with `base::names()`).

```suggestion
pkg_paths <- c(
  "DALEXtra_new" = test_path("testing_pkgs", "DALEXtra"),
  "rd2markdown_new" = test_path("testing_pkgs", "rd2markdown"),
  "exampleGood_new" = file.path(examples_path, "exampleGood"),
  "exampleOkay_new" = file.path(examples_path, "exampleOkay"),
  "exampleBad_new" = file.path(examples_path, "exampleBad")
)
```

2024-09-26 16:28 UTC, dgkf-roche commented on R/check_design.R
> +          }
Would be nice to test this behavior. You can mock `interactive()` to return `TRUE` and `menu()` to return a value to avoid requiring user input.

2024-09-27 13:52 UTC, maksymiuks commented on tests/testthat/test-checks_df.R
> +)
They are used later in tests but moved closer to the particular part it is used.

2024-09-27 17:40 UTC, dgkf-roche approved these changes
Pre-approving since all the requested changes are pretty minor.

2024-09-27 17:40 UTC, dgkf-roche commented on R/check_process.R
>  )
I don't think these are used anywhere now. Can we remove them?

2024-09-27 17:40 UTC, dgkf-roche commented on tests/testthat/test-checks_df.R
> +    c(R_CHECKED_CHECK_ARGS = "c('--some-option', '--other-option')",
`options` provides an interface to define how environment variables are parsed. It might be better to expect environment variables for command line flags to be space-delimited, ie

```
R_CHECKED_CHECK_ARGS = "--some-option --other-option"
```

Will leave a note near the definition of the variable to show how it could work

2024-09-27 17:40 UTC, dgkf-roche commented on R/options.R
> +)
This _should_ be as easy as

```r
  check_build_args = c(
    "--no-build-vignettes",
    "--no-manual"
  ),
  envvar_fn = envvar_str_split(delim = " "),

  "`character` vector of args passed to the R CMD check.",
  check_args = c(
    "--timings",
    "--ignore-vignettes",
    "--no-manual"
  ),
  envvar_fn = envvar_str_split(delim = " "),
)
```

However, I tested this change and realized there's a bug in `options` where this `delim` parameter has no effect. [Bug report filed](https://codeberg.org/dgkf/options/issues/22) and I'll publish a new minor release soon with this change.

For now we can just define this ourselves. Once `options` is fixed, it will be nice to use the helper function because it also produces better docs with a predefined description of how environment variables are processed.

```suggestion
  check_build_args = c(
    "--no-build-vignettes",
    "--no-manual"
  ),
  envvar_fn = function(raw, ...) trimws(strsplit(raw, " ")[[1]]),

  "`character` vector of args passed to the R CMD check.",
  check_args = c(
    "--timings",
    "--ignore-vignettes",
    "--no-manual"
  ),
  envvar_fn = function(raw, ...) trimws(strsplit(raw, " ")[[1]])
)
```

2024-09-30 10:20 UTC, maksymiuks commented on R/options.R
> +)
I'm sorry, but could you please elaborate a bit more on this? Is this parsing just for the docs or generally to alter the value? I generally understand your point and agree that using string _feels_ better. However, currently `rcmdcheck` and originally `devtools` expect these variables to be vectors rather than strings. I'm unsure if changing that standard is a good idea, especially since we are using rcmdcheck underneath. Unless there is something I'm missing in your suggestion.

2024-09-30 16:50 UTC, dgkf-roche commented on R/options.R
> +)
Yes, you're understanding that correctly. It's a function that gets applied to the raw environment variable value.

Passing R code as strings is full of potholes. Accidentally not closing parenthesis, escaping quotes, nesting quotes - all are easy mistakes. This tries to make the environment variable specification style as failure-mitigating as possible.

The generated docs will show a more specific message once this is built with the new patch release, or we can provide our own custom documentation via

```
envvar_fn = {
  f <- function(raw, ...) trimws(strsplit(raw, " ")[[1]])
  attr(f, "desc") <- "space-separated R CMD check flags"
  f
}
```

There's an internal function for helping with this, but all it does is assign this attribute.

2024-09-30 16:53 UTC, dgkf-roche commented on R/check_process.R
>  )
Just bumping this change. We should delete stale code.

2024-10-01 10:40 UTC, maksymiuks commented on R/check_process.R
>  )
These were removed just after starting this MR, sorry I didn't point it out

2024-10-01 11:35 UTC, maksymiuks commented on R/options.R
> +)
Thanks, I added parser! And what a great feature!

2024-10-01 12:13 UTC, merged